# Generated by Django 2.1 on 2018-09-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_no', models.IntegerField(primary_key=True, serialize=False)),
                ('airline_name', models.CharField(default='john doe', max_length=50)),
                ('no_of_seats', models.IntegerField(default=0)),
                ('source', models.CharField(default='Delhi', max_length=50)),
                ('destination', models.CharField(default='Mumbai', max_length=50)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='john', max_length=50)),
                ('last_name', models.CharField(default='doe', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='john', max_length=50)),
                ('last_name', models.CharField(default='doe', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('flight_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='john', max_length=50)),
                ('last_name', models.CharField(default='doe', max_length=50)),
                ('dob', models.DateField(default=0.0005025125628140704)),
                ('nationality', models.CharField(default='India', max_length=50)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('checked_in_status', models.BooleanField(default=0)),
                ('cleared_security_status', models.IntegerField(default=0)),
                ('flight_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Flight')),
            ],
        ),
    ]
