# Generated by Django 2.1 on 2018-09-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20180913_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
