# Generated by Django 2.1 on 2018-09-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20180913_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='flight_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flights.Flight'),
        ),
    ]
