# Generated by Django 2.0.5 on 2018-10-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20180913_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_no',
            field=models.IntegerField(default=1007, primary_key=True, serialize=False),
        ),
    ]
