# Generated by Django 2.0.5 on 2018-10-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20181018_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='flight_no',
            field=models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='flights.Flight'),
        ),
        migrations.AlterField(
            model_name='users',
            name='flight_no',
            field=models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='flights.Flight'),
        ),
    ]
